<template>
  <div @keyup.enter="this.sendData">
    <h1 class="text-center">Biotron change settings</h1>
    <DeviceSelector regex-name="Biotron" @device_changed="(x) => {this.device = x} "/>
    <PatchSelector :patches="this.patches" :key="this.forceRerender + this.patchRerender" :page_id="this.id"/>
    <GroupOfCommands name-of-group="BPM">
      <template v-slot:objects>
        <SliderCommand command-label="Plant Bpm" :key="this.forceRerender" :command-object="this.commands_data.plantBpm"/>
        <SliderCommand command-label="Note Off Percent" :key="this.forceRerender" :command-object="this.commands_data.noteOffPercent"/>
        <SliderCommand command-label="Light Bpm" :key="this.forceRerender" :command-object="this.commands_data.lightBpm"/>
      </template>
      <template v-slot:description>
        <p>BPM - how many notes from the plant will be generated per minute</p>
        <p>Note Off Percent - how many percent of the time the note will sound, where 100 is the full sound before the note changes, 50 is half the time the note is played</p>
        <p>Light Bpm - once every number of notes from the plant the note from the photoresistor will sound</p>
      </template>
    </GroupOfCommands>
    <GroupOfCommands name-of-group="Sensitivity (fib)">
      <template v-slot:objects>
        <SliderCommand command-label="Note Distance" :key="this.forceRerender" :command-object="this.commands_data.noteDistance"/>
        <SliderCommand command-label="First Value" :key="this.forceRerender" :command-object="this.commands_data.firstValue"/>
      </template>
      <template v-slot:description>
        <p>Sensitivity (fib) - Fibonacci parameter responsible for the note distribution curve</p>
      </template>
    </GroupOfCommands>
    <GroupOfCommands name-of-group="Smoothness">
      <template v-slot:objects>
        <SliderCommand :key="this.forceRerender" :command-object="this.commands_data.smoothness" />
      </template>
      <template v-slot:description>
        <p>Smoothness - the smoothness of the notes played, where 0 is an instant change in notes,
          99 is a smooth change (notes change over time)</p>
      </template>
    </GroupOfCommands>
    <GroupOfCommands name-of-group="Scale">
      <template v-slot:objects>
        <SelectCommand :key="this.forceRerender" :list-of-variants="this.scales" :command-object="commands_data.scale"/>
      </template>
      <template v-slot:description>
        <p>Scale - scale played from the device</p>
      </template>
    </GroupOfCommands>
    <GroupOfCommands name-of-group="Velocity">
      <template v-slot:objects>
        <GroupOfCommands name-of-group="Plant">
          <template v-slot:objects>
            <div class="row">
              <div class="col">
                  <label for="randomPlantVelSwitch">Humanize</label>
                  <SwitchComponent id="randomPlantVelSwitch" :model-value="this.commands_data.randomPlantVelocity"/>
              </div>
              <div class="col">
                  <label for="plantVelDis">Mute</label>
                  <SwitchComponent id="plantVelDis" :model-value="commands_data.plant_no_velocity"/>
              </div>
            </div>
            <div v-if="!commands_data.plant_no_velocity.value">
              <div v-if="!this.commands_data.randomPlantVelocity.value">
                <SliderCommand :key="this.forceRerender"
                               :command-object="commands_data.maxPlantVelocity"/>
              </div>
              <div v-else>
                <SliderRangeCommand :key="this.forceRerender"
                                    :max-command-object="commands_data.maxPlantVelocity"
                                    :min-command-object="commands_data.minPlantVelocity"/>
              </div>
            </div>
          </template>
          <template v-slot:description>
            <p>Plant - responsible for the notes generated by the plant</p>
          </template>
        </GroupOfCommands>
        <GroupOfCommands name-of-group="Light">
          <template v-slot:objects>
            <div class="row">
              <div class="col">
                <label for="randomLightVelSwitch">Humanize</label>
                <SwitchComponent id="randomLightVelSwitch" :model-value="this.commands_data.randomLightVelocity"/>
              </div>
              <div class="col">
                <label for="lightVelDis">Mute</label>
                <SwitchComponent id="lightVelDis" :model-value="commands_data.light_no_velocity"/>
              </div>
            </div>
            <div class="row" v-if="!commands_data.light_no_velocity.value">
              <div v-if="!this.commands_data.randomLightVelocity.value">
                <SliderCommand :key="this.forceRerender"
                                          :command-object="commands_data.maxLightVelocity"/>
              </div>
              <div v-else>
                <SliderRangeCommand :key="this.forceRerender"
                                               :max-command-object="commands_data.maxLightVelocity"
                                               :min-command-object="commands_data.minLightVelocity"/>
              </div>
            </div>
          </template>
          <template v-slot:description>
            <p>Light - responsible for notes generated from the photoresistor</p>
          </template>
        </GroupOfCommands>
      </template>
      <template v-slot:description>
        <p>Velocity - pressing force</p>
        <p>Humanize - Velocity randomization at a controlled interval</p>
        <p>Mute - disable note generation from the channel</p>
      </template>
    </GroupOfCommands>
    <GroupOfCommands name-of-group="Ultra sensitivity">
      <template v-slot:objects>
        <DisableCommand :key="this.forceRerender" :command-object="commands_data.randomness"/>
      </template>
      <template v-slot:description>
        <p>Ultra sensitivity - Increases the sensitivity of generation from a plant</p>
      </template>
    </GroupOfCommands>
    <GroupOfCommands name-of-group="Same Note">
      <template v-slot:objects>
        <SliderCommand :key="this.forceRerender" :command-object="commands_data.same_note" />
      </template>
      <template v-slot:description>
        <p>Same Note - notes that are played only when changing notes with a customizable step,
          where 1 - produces a note if the notes have changed by 1 note, 10 if there has been a shift by 10 notes</p>
      </template>
    </GroupOfCommands>
    <GroupOfCommands name-of-group="Light Notes Range">
      <template v-slot:objects>
        <SliderRangeCommand
            :key="this.forceRerender"
            :max-command-object="commands_data.max_range_light_note"
            :min-command-object="commands_data.min_range_light_note"/>
      </template>
      <template v-slot:description>
        <p>Light Notes Range - setting the range of notes played from the photoresistor (lower and upper limits are set)</p>
      </template>
    </GroupOfCommands>
    <button @click="this.sendData" :disabled="this.device === null" class="btn btn-primary mb-1" style="width: 70%">Send</button>
<!--    <button @click="this.returnDefault" class="btn btn-primary mb-1" style="width: 70%">Set Default</button>-->
    <button @click="this.createPreset" class="btn btn-primary mb-1" style="width: 70%">Create Preset</button>
    <FileDropArea name="Drop Preset Here" @get_drop="(e) => loadDataFromPreset(e)"/>
    <GroupOfCommands>
      <template v-slot:description>
        <p>Send - sending settings to the device</p>
        <p>Set Default - basic settings are set on the site (to apply them, you need to click Send)</p>
        <p>Create Preset - saves settings to a file</p>
        <p>Drop Preset Here - you need to transfer the file there by drag drop, or by clicking on the button, select the settings file.</p>
      </template>
    </GroupOfCommands>
  </div>
</template>

<script>
import SliderCommand from "@/components/system/SliderCommand.vue";
import GroupOfCommands from "@/components/system/GroupOfCommands.vue";
import SelectCommand from "@/components/system/SelectCommand.vue";
import DeviceSelector from "@/components/system/DeviceSelector.vue";
import { SysExCommand, sleep } from "@/assets/js/SysExCommand"
import DisableCommand from "@/components/system/DisableCommand.vue";
import FileDropArea from "@/components/system/FileDropArea.vue";
import { saveAs } from '@progress/kendo-file-saver';
import SliderRangeCommand from "@/components/system/SliderRangeCommand.vue";
import SwitchComponent from "@/components/system/Switch.vue";
import { BiotronDb } from "@/assets/js/PatchBiotrons"
import PatchSelector from "@/components/system/PatchSelector.vue";

export default  {
  components: {
    // eslint-disable-next-line vue/no-unused-components
    PatchSelector,
    SwitchComponent,
    SliderRangeCommand,
    FileDropArea,
    DisableCommand, DeviceSelector, SelectCommand, GroupOfCommands, SliderCommand},
  props: {
    id: {
      type: String,
      required: true,
    },
  },
  methods: {
    sendData() {
      if (this.device) {
        let extraComp = []
        if (this.randomPlantVelocity) {
          this.device.send([240, 11, 16, 127, 247])
          sleep(100);
        } else {
          this.device.send([240, 11, 16, 0, 247])
          sleep(100);
        }
        if (this.commands_data.plant_no_velocity) {
          this.device.send([240, 11, 5, 0, 247])
          sleep(100)
          this.device.send([240, 11, 15, 0, 247])
          sleep(100)
          extraComp.push("minPlantVelocity")
          extraComp.push("maxPlantVelocity")
        }
        if (this.commands_data.light_no_velocity) {
          this.device.send([240, 11, 6, 0, 247])
          sleep(100)
          this.device.send([240, 11, 17, 0, 247])
          sleep(100)
          extraComp.push("minLightVelocity")
          extraComp.push("maxLightVelocity")
        }
        if (this.randomLightVelocity) {
          this.device.send([240, 11, 18, 127, 247])
          sleep(100);
        } else {
          this.device.send([240, 11, 18, 0, 247])
          sleep(100);
        }
        for (let comm in this.commands_data) {
          if (!extraComp.includes(comm)) {

            this.commands_data[comm].sendToMidi(this.device)
            sleep(100);
          }
        }
      }
    },

    saveData() {
      let state = []
      for (let item in this.commands_data) {
        state.push(this.commands_data[item].toShortDict())
      }

      this.db.updatePatch(localStorage.getItem(this.id), state)
    },

    async loadData() {
      let preset = await this.db.getPatch(localStorage.getItem(this.id))
      if (!preset) {
        localStorage.setItem(this.id, 1)
        preset = await this.db.getPatch(localStorage.getItem(this.id))
      }

      for (let item of preset.data) {
        this.commands_data[item.name].set_value(item.value);
      }

      this.forceRerender++;
    },
    returnDefault() {
      this.randomPlantVelocity = false
      this.randomLightVelocity = false
      for (let comm in this.commands_data) {
        this.commands_data[comm].set_default();
      }
      this.saveData();
      this.forceRerender += 1
      this.device.send([240, 11, 7, 247])
    },
    createPreset() {
      let state = []
      for (let item in this.commands_data) {
        state.push(this.commands_data[item].toShortDict())
      }

      let value = {"commands": state}
      let myFile = new File([JSON.stringify(value)], "biotron_preset.txt",
          {type: "text/plain;charset=utf-8"})
      saveAs(myFile, "biotron_preset.txt");
    },
    async loadDataFromPreset(e) {
      await this.patchChanged();
      for (let item of JSON.parse(e).commands) {
        this.commands_data[item.name].set_value(item.value);
      }
      this.saveData();
      this.forceRerender++;
    },
    async patchChanged() {
      let patch_id = parseInt(localStorage.getItem(this.id));

      if (this.patches.find(item => item.id === patch_id).saved) {
        patch_id = await this.db.getUnsavedPatch();
        this.patches = await this.db.getPatch();
        localStorage.setItem(this.id, patch_id);
      }
      this.saveData();
    },
  },
  data() {
    return {
      scales: ["Major", "Minor", "Chrom", "Dorian", "Mixolydian",
        "Lydian", "Wholetone", "Minblues", "Minpen",
        "Majpen", "Diminished"],
      device: null,
      forceRerender: 0,
      patchRerender: 0,
      db: {
        type: BiotronDb
      },
      patches: [],
      patch_id: 0,
      commands_data: {
        "plantBpm": new SysExCommand( {
          name: "plantBpm",
          number_command: 0,
          default_value: 60,
          max_value: 1000
        }),
        "lightBpm": new SysExCommand( {
          name: "lightBpm",
          number_command: 9,
          default_value: 4,
          max_value: 30
        }),
        "noteOffPercent": new SysExCommand({
          name: "noteOffPercent",
          number_command: 12,
          default_value: 100,
          max_value: 100
        }),
        "noteDistance": new SysExCommand({
          name: "noteDistance",
          number_command: 1,
          default_value: 50,
          max_value: 100
        }),
        "firstValue": new SysExCommand({
          name: "firstValue",
          number_command: 2,
          default_value: 10,
          max_value: 100
        }),
        "smoothness": new SysExCommand({
          name: "smoothness",
          number_command: 3,
          max_value: 99
        }),
        "scale": new SysExCommand( {
          name: "scale",
          number_command: 4,
          default_value: 0
        }),
        "minPlantVelocity": new SysExCommand({
          name: "minPlantVelocity",
          number_command: 15,
          default_value: 74,
          max_value: 127
        }),
        "maxPlantVelocity": new SysExCommand({
          name: "maxPlantVelocity",
          number_command: 5,
          default_value: 75,
          max_value: 127
        }),
        "minLightVelocity": new SysExCommand({
          name: "minLightVelocity",
          number_command: 17,
          default_value: 74,
          max_value: 127
        }),
        "maxLightVelocity": new SysExCommand({
          name: "maxLightVelocity",
          number_command: 6,
          default_value: 75,
          max_value: 127
        }),
        "randomness": new SysExCommand({
          name: "randomness",
          number_command: 10,
          default_value: 0
        }),
        "same_note": new SysExCommand({
          name: "same_note",
          number_command: 11,
          default_value: 0,
          max_value: 10
        }),
        "min_range_light_note": new SysExCommand({
          name: "min_range_light_note",
          number_command: 13,
          default_value: 24,
        }),
        "max_range_light_note": new SysExCommand({
          name: "max_range_light_note",
          number_command: 14,
          default_value: 48,
        }),
        "plant_no_velocity": new SysExCommand({
          name: "plant_no_velocity",
          default_value: 0,
          sendable: false,
        }),
        "light_no_velocity": new SysExCommand({
          name: "light_no_velocity",
          default_value: 0,
          sendable: false,
        }),
        "randomPlantVelocity": new SysExCommand({
          name: "randomPlantVelocity",
          default_value: 0,
          sendable: false,
        }),
        "randomLightVelocity": new SysExCommand({
          name: "randomLightVelocity",
          default_value: 0,
          sendable: false,
        }),
      },

    }
  },
  async created() {
    if (localStorage.getItem(this.id) === undefined) {
      localStorage.setItem(this.id, "1")
    }

    this.db = new BiotronDb();
    await this.db.openDB();

    this.patches = await this.db.getPatch();
    this.patch_id = parseInt(localStorage.getItem(this.id));

    await this.loadData()
    this.forceRerender++;


  },
  mounted() {
    document.addEventListener( 'keyup', event => {
      if (event.code === 'Enter') this.sendData();
    })
    document.addEventListener( 'InputChanged', async () => {
      await this.patchChanged();
      this.patchRerender++;
    })
    document.addEventListener( 'PatchChanged', async () => {
      await this.loadData();
      this.forceRerender++;
    })
    document.addEventListener("PatchSave",  async (ev) => {
      this.db.savePatch(localStorage.getItem(this.id), ev.detail)
      this.patches = await this.db.getPatch()
      this.patchRerender++;
    })
    document.addEventListener( 'PatchDelete', async () => {
      this.db.deletePatch(parseInt(localStorage.getItem(this.id)))
      localStorage.setItem(this.id, "1")
      this.patches = await this.db.getPatch()
      await this.loadData();
      this.forceRerender++;
    })
  }
}
</script>

<style scoped>

</style>